// <auto-generated />
namespace Ninesky.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class 第一次初始化 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(第一次初始化));
        
        string IMigrationMetadata.Id
        {
            get { return "201509160240007_第一次初始化"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
